
### playlist request
POST {{local}}/api/v1/playlist
Content-Type: application/json

{
  "url": "iptv.m3u"
}

### config request
GET {{local}}/api/v1/config
Content-Type: application/json

### auth
POST {{local}}/auth/token
Content-Type: application/json

{"username": "test", "password": "test"}

### m3u playlist
GET {{local}}/m3u?username={{username}}&password={{password}}

### m3u playlist - form auth
POST {{local}}/m3u
Content-Type: application/x-www-form-urlencoded

username={{username}}&password={{password}}

### m3u playlist
GET {{local}}/m3u?username={{username}}&password={{password}}

### xtream login
GET {{local}}/player_api.php?username={{username}}&password={{password}}

### xtream live_categories
GET {{local}}/player_api.php?username={{username}}&password={{password}}&action=get_live_categories

### xtream live_streams
GET {{local}}/player_api.php?username={{username}}&password={{password}}&action=get_live_streams&category_id=1

### xtream vod_categories
GET {{local}}/player_api.php?username={{username}}&password={{password}}&action=get_vod_categories

### xtream vod streams
GET {{local}}/player_api.php?username={{username}}&password={{password}}&action=get_vod_streams&category_id=29

### xtream vod info
GET {{local}}/player_api.php?username={{username}}&password={{password}}&action=get_vod_info&vod_id=38497

### xtream series_categories
GET {{local}}/player_api.php?username={{username}}&password={{password}}&action=get_series_categories

### xtream series
GET {{local}}/player_api.php?username={{username}}&password={{password}}&action=get_series

### xtream series for category
GET {{local}}/player_api.php?username={{username}}&password={{password}}&action=get_series&category_id=12


### xtream series info
GET {{local}}/player_api.php?username={{username}}&password={{password}}&action=get_series_info&series_id=3529369776

### xtream series stream
 GET {{local}}/series/{{username}}/{{password}}/201422

### get stream
{{local}}/m3u-stream/live/{{username}}/{{password}}/667
