FROM gcr.io/distroless/base-debian12 AS build

# Scratch Final container
FROM scratch AS scratch-final
WORKDIR /app

COPY --from=build /usr/share/zoneinfo /usr/share/zoneinfo
COPY --from=build /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

COPY ./tuliprox ./
COPY ./web ./web
COPY ./resources ./resources

CMD ["/app/tuliprox", "-s", "-p", "/app/config"]

# Alpine Final container
FROM alpine:latest AS alpine-final

RUN apk add --no-cache bash curl strace tcpdump bind-tools nano ca-certificates tini

WORKDIR /app

COPY ./tuliprox ./
COPY ./web ./web
COPY ./resources ./resources
# config should be mounted as volume
# COPY ./config ./config

ENTRYPOINT ["/sbin/tini", "--", "/app/tuliprox"]
CMD ["-s", "-p", "/app/config"]