FROM gcr.io/distroless/base-debian12 as build

# Scratch Final container
FROM scratch as scratch-final
WORKDIR /

COPY --from=build /usr/share/zoneinfo /usr/share/zoneinfo
COPY --from=build /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

COPY ./m3u-filter /
COPY ./web /web
COPY ./channel_unavailable.ts ./channel_unavailable.ts
COPY ./user_connections_exhausted.ts ./user_connections_exhausted.ts

CMD ["./m3u-filter", "-s", "-p", "/config"]

# Alpine Final container
FROM alpine:latest as alpine-final

RUN apk add --no-cache bash curl strace tcpdump bind-tools nano ca-certificates tini

WORKDIR /app

COPY ./m3u-filter .
COPY ./web ./web
COPY ./freeze_frame.ts ./freeze_frame.ts
# config should be mounted as volume
# COPY ./config ./config

ENTRYPOINT ["/sbin/tini", "--", "/app/m3u-filter"]
CMD ["-s", "-p", "/app/config"]